import {openDB,getAll,getOne,putOne,putMany,deleteOne,getMeta,setMeta,snapshot,replaceSnapshot,ensureInitialData,migrateV5LocalIfNeeded,uuid,iso,todayKey,stamp} from './storage.js?v=6.2.1';
import {gamePitchingSummary,battingSummary,defenseSummary,baserunningSummary,trainingSummary,workloadSummary,todaySummary,totalTLU,seriesByDate,localDate,dateShift,OFFICIAL_PITCH_TYPES,STRIKE_PITCH_TYPES,GAME_TLU,round2} from './analytics.js?v=6.2.1';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const storeNames=['athletes','gameDays','batterFaced','plateAppearances','gameEvents','trainingSets'];
let data={athletes:[],gameDays:[],batterFaced:[],plateAppearances:[],gameEvents:[],trainingSets:[]};
let ui={view:'home',inputDate:todayKey(),inputMode:'game',domain:'pitching',historyDate:'all',historyMode:'all',historyDomain:'all',analysisSource:'game',analysisPeriod:'30',analysisDate:todayKey(),analysisDomain:'pitching',ownSide:'all',oppSide:'all',pendingBatterSide:null,pendingOwnPitchSide:null,pendingBatSide:null,pendingOppPitcherSide:null,inPlayContext:null,quantity:10};
let activeAthleteId=null,toastTimer=null,undoTimer=null,lastDeleted=null,deferredInstallPrompt=null,syncTimer=null,staticEventsBound=false;
const cloud={client:null,session:null,configured:false,syncing:false,lastSync:Number(localStorage.getItem('btV6LastSync')||0)};

const LABELS={
  ball:'BALL',called:'루킹',swinging:'헛스윙',foul:'파울',inplay:'IN PLAY',hbp:'HBP',pickoff_normal:'견제 정상',pickoff_error:'견제 악송구',game_warmup:'연습투구',
  taken_ball:'볼 지켜봄',taken_strike:'스트라이크 지켜봄',swinging_strike:'헛스윙',in_play:'IN PLAY',
  fielding_play:'수비 플레이',steal_attempt:'도루 시도',advancement:'추가 진루',
  throwing:'투구',DRY_SWING:'빈스윙',TEE:'티',TOSS:'토스',BP:'배팅볼',MACHINE:'머신',LIVE:'라이브',FIELDING:'포구',THROWING:'송구',GROUND_BALL:'땅볼',FLY_BALL:'플라이',DOUBLE_PLAY:'병살',RELAY:'중계플레이',FOOTWORK:'풋워크',OTHER:'기타',STEAL_START:'도루 스타트',LEAD_REACTION:'리드/반응',BASE_RUNNING:'베이스러닝',SLIDING:'슬라이딩',SPRINT:'스프린트'
};
const DOMAIN_LABEL={pitching:'투구',hitting:'타격',defense:'수비',baserunning:'주루'};

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmtDate(k){if(!k)return '';const [y,m,d]=k.split('-');return `${y}.${m}.${d}`;}
function fmtShort(k){if(!k)return '';const [,m,d]=k.split('-');return `${Number(m)}/${Number(d)}`;}
function fmtTime(v){try{return new Date(v).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});}catch{return '';}}
function pct(v,d=1){return v==null||Number.isNaN(v)?'—':`${(v*100).toFixed(d)}%`;}
function dec(v){return v==null||Number.isNaN(v)?'—':Number(v).toFixed(3).replace(/^0/,'');}
function n2(v){const x=round2(v);return Number.isInteger(x)?String(x):x.toFixed(2).replace(/0$/,'');}
function active(list){return (list||[]).filter(x=>!x.deletedAt);}
function athlete(){return active(data.athletes).find(a=>a.id===activeAthleteId)||active(data.athletes)[0];}
function refreshDataStore(store,items){data[store]=items;}
async function reloadData(){for(const s of storeNames)refreshDataStore(s,await getAll(s));activeAthleteId=await getMeta('activeAthleteId',active(data.athletes)[0]?.id||null);}
function markLocal(obj){return stamp(obj,{dirty:true});}
async function save(store,obj,{render=true,sync=true}={}){markLocal(obj);await putOne(store,obj);const i=data[store].findIndex(x=>x.id===obj.id);if(i>=0)data[store][i]=obj;else data[store].push(obj);if(render)renderAll();if(sync)scheduleSync();return obj;}
function recordsFor(store){return active(data[store]).filter(x=>x.athleteId===activeAthleteId);}
function getGameDay(date=ui.inputDate){return recordsFor('gameDays').find(x=>x.activityDate===date);}
async function ensureGameDay(date=ui.inputDate){let x=getGameDay(date);if(x)return x;x={id:uuid(),athleteId:activeAthleteId,activityDate:date,ownerId:cloud.session?.user?.id||null,deletedAt:null,createdAt:iso(),updatedAt:iso(),clientUpdatedAt:Date.now(),dirty:true};await save('gameDays',x,{render:false});return x;}
function currentBF(date=ui.inputDate){return recordsFor('batterFaced').filter(x=>x.activityDate===date&&!x.completed).sort((a,b)=>b.sequenceNo-a.sequenceNo)[0]||null;}
function currentPA(date=ui.inputDate){return recordsFor('plateAppearances').filter(x=>x.activityDate===date&&!x.completed).sort((a,b)=>b.sequenceNo-a.sequenceNo)[0]||null;}
function bfEvents(id){return recordsFor('gameEvents').filter(e=>e.parentType==='batter_faced'&&e.parentId===id).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));}
function paEvents(id){return recordsFor('gameEvents').filter(e=>e.parentType==='plate_appearance'&&e.parentId===id).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));}
function countBS(events,type='pitching'){
  let b=0,s=0;for(const e of events){if(type==='pitching'){if(e.eventType==='ball')b++;else if(['called','swinging','foul','inplay'].includes(e.eventType)){if(!(e.eventType==='foul'&&s>=2))s++;}}else{if(e.eventType==='taken_ball')b++;else if(['taken_strike','swinging_strike','foul','in_play'].includes(e.eventType)){if(!(e.eventType==='foul'&&s>=2))s++;}}}return {b,s};
}
function lastCompleted(kind,date=ui.inputDate){const list=kind==='bf'?recordsFor('batterFaced'):recordsFor('plateAppearances');return list.filter(x=>x.activityDate===date&&x.completed).sort((a,b)=>b.sequenceNo-a.sequenceNo)[0]||null;}
function nextSequence(store,date){return Math.max(0,...recordsFor(store).filter(x=>x.activityDate===date).map(x=>Number(x.sequenceNo)||0))+1;}

function withTimeout(promise,ms,label){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(`${label} 시간이 초과되었습니다.`)),ms))]);}
async function init(){
  // Bind navigation first so a slow local DB can never leave a completely dead screen.
  bindStaticEvents();registerPWA();
  $('#todayLabel').textContent=fmtDate(todayKey());
  await withTimeout(openDB(),6000,'로컬 데이터베이스 열기');
  await withTimeout(migrateV5LocalIfNeeded(),12000,'기존 데이터 변환');
  await withTimeout(ensureInitialData(),6000,'초기 데이터 준비');
  await withTimeout(reloadData(),8000,'기록 불러오기');
  ui.inputDate=todayKey();ui.analysisDate=todayKey();
  renderAll();
  window.__BT_APP_READY__=true;
  const boot=$('#bootError');if(boot)boot.hidden=true;
  initCloud().catch(err=>{console.error('Cloud init failed',err);renderCloudStatus('error','동기화 초기화 실패');});
}

function setView(v){ui.view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));const titles={home:'홈',input:'입력',history:'기록',analysis:'분석',settings:'설정'};$('#pageTitle').textContent=titles[v]||'';if(v==='history')renderHistory();if(v==='analysis')renderAnalysis();window.scrollTo({top:0,behavior:'smooth'});}
function renderAll(){renderHeader();renderHome();renderInput();renderHistory();renderAnalysis();renderSettings();}
function renderHeader(){const a=athlete();$('#activeAthleteName').textContent=a?.name||'선수';$('#athleteInitial').textContent=(a?.name||'P').slice(0,1);$('#todayLabel').textContent=fmtDate(todayKey());}
function showToast(title,message='',type=''){const el=$('#toast');el.className=`toast show ${type}`;el.innerHTML=`<b>${esc(title)}</b>${message?`<span>${esc(message)}</span>`:''}`;if(type==='complete'){const panel=$('.entry-panel');panel?.classList.add('completion-flash');setTimeout(()=>panel?.classList.remove('completion-flash'),360);}clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1200);}
function showModal(id){$('#'+id).hidden=false;}function hideModal(id){$('#'+id).hidden=true;}

function renderHome(){
  const a=athlete();if(!a)return;const date=todayKey();const s=todaySummary(data,{athleteId:a.id,date});
  $('#homeDateCaption').textContent=`${fmtDate(date)} · ${a.name}`;$('#homeTotalTLU').textContent=n2(s.totalTLU);$('#homeGameTLU').textContent=n2(s.gameTLU);$('#homeTrainingTLU').textContent=n2(s.training.tlu);$('#homeOfficialPitches').textContent=s.game.pitching.officialPitches;const defenseTrainingThrows=active(data.trainingSets).filter(x=>x.athleteId===a.id&&x.activityDate===date&&x.domain==='defense').reduce((sum,x)=>sum+Number(x.metadata?.throwCount||0),0);$('#homeTotalThrows').textContent=s.game.pitching.totalGameThrows+s.game.defense.throwAttempts+(s.training.byDomain.pitching?.volume||0)+defenseTrainingThrows;
  const p=s.game.pitching,h=s.game.hitting,d=s.game.defense,b=s.game.baserunning;
  $('#homeGameSummary').innerHTML=[
    ['투구',`${p.officialPitches} pitches · Strike ${pct(p.strikePct,0)}`],['타격',`${h.PA} PA · ${h.H} H · OPS ${h.PA?dec(h.OPS):'—'}`],['수비',`${d.plays} plays · 포구 ${pct(d.fieldingSuccessPct,0)}`],['주루',`SB ${b.sb} · CS ${b.cs}`]
  ].map(x=>`<div class="summary-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
  const t=s.training.byDomain;$('#homeTrainingSummary').innerHTML=[
    ['투구',`${t.pitching.volume||0} throws · ${n2(t.pitching.tlu||0)} TLU`],['타격',`${t.hitting.volume||0} swings`],['수비',`${t.defense.volume||0} reps · ${n2(t.defense.tlu||0)} TLU`],['주루',`${t.baserunning.volume||0} reps`]
  ].map(x=>`<div class="summary-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
}

function renderInput(){
  $('#activityDateInput').value=ui.inputDate;$$('#inputModeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===ui.inputMode));$$('#domainTabs button').forEach(b=>b.classList.toggle('active',b.dataset.domain===ui.domain));
  renderInputSummary();renderInputForm();renderRecent();
}

function renderInputSummary(){
  const el=$('#inputSummary'),a=athlete();if(!a)return;
  const total=totalTLU(data,{athleteId:a.id,date:ui.inputDate});
  if(ui.inputMode==='game'&&ui.domain==='pitching'){
    const s=gamePitchingSummary(data,{athleteId:a.id,date:ui.inputDate}),bf=currentBF(),prev=lastCompleted('bf');
    el.innerHTML=`<div class="performance-title"><div><p class="section-kicker">PITCHING</p><h2>${fmtDate(ui.inputDate)}</h2></div></div>
    ${sideButtonsPitching(bf)}
    <div class="big-stat"><strong>${s.officialPitches}</strong><span>OFFICIAL PITCHES</span></div><div class="big-stat"><strong>${n2(s.gameTLU)}</strong><span>GAME TLU · TODAY TOTAL ${n2(total)}</span></div>
    ${perfRows([['STRIKE',pct(s.strikePct,0)],['1ST STRIKE',pct(s.firstPitchStrikePct,0)],['BF',s.bf],['K',s.k],['BB',s.bb],['HBP',s.hbp],['P / BF',s.pitchesPerBatter?Number(s.pitchesPerBatter).toFixed(2):'—'],['PICKOFF',`${s.pickoffs} / ERR ${s.pickoffErrors}`],['WARM-UP',s.warmups]])}
    ${prev?`<div class="prev-result"><span>직전 타자</span><b>#${prev.sequenceNo} · ${bfEvents(prev.id).length}구 · ${esc(prev.result||'완료')}</b></div>`:''}`;
  } else if(ui.inputMode==='game'&&ui.domain==='hitting'){
    const s=battingSummary(data,{athleteId:a.id,date:ui.inputDate}),pa=currentPA(),prev=lastCompleted('pa');
    el.innerHTML=`<div class="performance-title"><div><p class="section-kicker">BATTING</p><h2>${fmtDate(ui.inputDate)}</h2></div></div>${sideButtonsBatting(pa)}
    <div class="big-stat"><strong>${s.PA}</strong><span>PLATE APPEARANCES</span></div><div class="big-stat"><strong>${s.H}</strong><span>HITS</span></div>
    ${perfRows([['AVG',dec(s.AVG)],['OBP',dec(s.OBP)],['SLG',dec(s.SLG)],['OPS',s.PA?dec(s.OPS):'—'],['SWINGS',s.swings],['WHIFF',s.whiffs],['CONTACT',pct(s.contactPct,0)],['SO',s.SO]])}
    ${prev?`<div class="prev-result"><span>직전 타석</span><b>#${prev.sequenceNo} · ${paEvents(prev.id).length}구 · ${esc(prev.result||'완료')}</b></div>`:''}`;
  } else if(ui.inputMode==='game'&&ui.domain==='defense'){
    const s=defenseSummary(data,{athleteId:a.id,date:ui.inputDate});el.innerHTML=`<div class="performance-title"><div><p class="section-kicker">DEFENSE</p><h2>${fmtDate(ui.inputDate)}</h2></div></div><div class="big-stat"><strong>${s.plays}</strong><span>DEFENSIVE PLAYS</span></div>${perfRows([['포구 성공',pct(s.fieldingSuccessPct,0)],['송구 성공',pct(s.throwSuccessPct,0)],['포구 실패',s.field.failed||0],['악송구',s.throws.error||0],['수비 송구 TLU',n2(s.throwTLU)]])}`;
  } else if(ui.inputMode==='game'&&ui.domain==='baserunning'){
    const s=baserunningSummary(data,{athleteId:a.id,date:ui.inputDate});el.innerHTML=`<div class="performance-title"><div><p class="section-kicker">BASERUNNING</p><h2>${fmtDate(ui.inputDate)}</h2></div></div><div class="big-stat"><strong>${pct(s.sbPct,0)}</strong><span>SB SUCCESS</span></div>${perfRows([['SB',s.sb],['CS',s.cs],['ATTEMPTS',s.attempts]])}`;
  } else {
    const s=trainingSummary(data,{athleteId:a.id,date:ui.inputDate,domain:ui.domain}),all=trainingSummary(data,{athleteId:a.id,date:ui.inputDate});const d=s.byDomain[ui.domain]||{volume:0,tlu:0};
    el.innerHTML=`<div class="performance-title"><div><p class="section-kicker">TRAINING · ${DOMAIN_LABEL[ui.domain].toUpperCase()}</p><h2>${fmtDate(ui.inputDate)}</h2></div></div><div class="big-stat"><strong>${d.volume||0}</strong><span>${trainingUnitLabel(ui.domain)}</span></div><div class="big-stat"><strong>${n2(d.tlu||0)}</strong><span>${DOMAIN_LABEL[ui.domain]} TLU · SELECTED DATE TOTAL ${n2(total)}</span></div>${trainingBreakdownHtml(s)}`;
  }
}
function perfRows(rows){return rows.map(([k,v])=>`<div class="perf-row"><span>${k}</span><b>${v}</b></div>`).join('');}
function trainingUnitLabel(d){return d==='pitching'?'THROWS':d==='hitting'?'SWINGS':'REPS';}
function trainingBreakdownHtml(s){const entries=Object.entries(s.byType).sort((a,b)=>b[1]-a[1]).slice(0,8);return entries.length?entries.map(([k,v])=>`<div class="perf-row"><span>${esc(LABELS[k]||k)}</span><b>${v}</b></div>`).join(''):'<div class="prev-result"><span>아직 기록 없음</span><b>오른쪽에서 훈련 세트를 추가하세요.</b></div>';}
function sideButtonsPitching(bf){const a=athlete();const own=bf?.pitcherSide||ui.pendingOwnPitchSide||(a?.throws==='S'?null:a?.throws);const opp=bf?.batterSide||ui.pendingBatterSide;return `<div class="field-group"><span>내 투구</span><div class="side-context">${sideBtn('pitcher','R','우투',own)}${sideBtn('pitcher','L','좌투',own)}</div></div><div class="field-group"><span>현재 상대 타자</span><div class="side-context">${sideBtn('batter','', '? 미입력',opp)}${sideBtn('batter','R','우타',opp)}${sideBtn('batter','L','좌타',opp)}</div></div>`;}
function sideButtonsBatting(pa){const a=athlete();const own=pa?.batterSide||ui.pendingBatSide||(a?.bats==='S'?null:a?.bats);const opp=pa?.pitcherSide||ui.pendingOppPitcherSide;return `<div class="field-group"><span>내 타격</span><div class="side-context">${sideBtn('bat','R','우타',own)}${sideBtn('bat','L','좌타',own)}</div></div><div class="field-group"><span>현재 상대 투수</span><div class="side-context">${sideBtn('oppPitcher','', '? 미입력',opp)}${sideBtn('oppPitcher','R','우투',opp)}${sideBtn('oppPitcher','L','좌투',opp)}</div></div>`;}
function sideBtn(kind,val,label,current){return `<button type="button" data-side-kind="${kind}" data-side-value="${val}" class="${(current||'')===val?'active':''}">${label}</button>`;}

function renderInputForm(){const el=$('#inputForm');if(ui.inputMode==='game'){if(ui.domain==='pitching')el.innerHTML=gamePitchingForm();else if(ui.domain==='hitting')el.innerHTML=gameBattingForm();else if(ui.domain==='defense')el.innerHTML=gameDefenseForm();else el.innerHTML=gameBaserunningForm();}else{el.innerHTML=trainingForm(ui.domain);}bindDynamicFormEvents();}
function gamePitchingForm(){const bf=currentBF(),bs=bf?countBS(bfEvents(bf.id),'pitching'):{b:0,s:0};return `<div class="entry-title"><div><p class="section-kicker">OFFICIAL PITCH</p><h2>PITCHING</h2><p>타자에게 던진 공은 1구 = 1.00 TLU</p></div><span class="microcopy">${bf?`타자 #${bf.sequenceNo}`:'새 타자'}</span></div><div class="count-balls"><span>B</span>${[1,2,3,4].map(i=>`<i class="count-dot ${i<=bs.b?'on':''}">${i}</i>`).join('')}<span>S</span>${[1,2,3].map(i=>`<i class="count-dot ${i<=bs.s?'on':''}">${i}</i>`).join('')}</div><button class="pitch-main" data-pitch="ball"><b>BALL</b><span>Official pitch +1</span></button><div class="action-grid"><button class="action-btn strike" data-pitch="called"><b>루킹</b><span>CALLED STRIKE</span></button><button class="action-btn strike" data-pitch="swinging"><b>헛스윙</b><span>SWINGING STRIKE</span></button><button class="action-btn" data-pitch="foul"><b>파울</b><span>FOUL</span></button><button class="action-btn inplay" data-pitch="inplay"><b>IN PLAY</b><span>결과 선택</span></button></div><button class="action-btn hbp full" style="margin-top:10px" data-pitch="hbp"><b>사구 HBP</b><span>타자 종료</span></button><div class="section-divider"><span>ARM LOAD</span></div><div class="load-actions"><button data-game-throw="pickoff_normal"><b>견제 정상</b><span>+0.85 TLU</span></button><button data-game-throw="pickoff_error"><b>견제 악송구</b><span>+0.85 TLU</span></button><button data-game-throw="game_warmup"><b>연습투구</b><span>+1.00 TLU</span></button></div>`;}
function gameBattingForm(){const pa=currentPA(),bs=pa?countBS(paEvents(pa.id),'batting'):{b:0,s:0};return `<div class="entry-title"><div><p class="section-kicker">PLATE APPEARANCE</p><h2>BATTING</h2><p>경기 중에는 매 구 반응만 빠르게 기록하고, 영상 분석에서 상세정보를 추가할 수 있습니다.</p></div><span class="microcopy">${pa?`타석 #${pa.sequenceNo}`:'새 타석'}</span></div><div class="count-balls"><span>B</span>${[1,2,3,4].map(i=>`<i class="count-dot ${i<=bs.b?'on':''}">${i}</i>`).join('')}<span>S</span>${[1,2,3].map(i=>`<i class="count-dot ${i<=bs.s?'on':''}">${i}</i>`).join('')}</div><button class="pitch-main" data-bat-pitch="taken_ball"><b>볼 지켜봄</b><span>TAKEN BALL</span></button><div class="action-grid"><button class="action-btn strike" data-bat-pitch="taken_strike"><b>스트라이크 지켜봄</b><span>CALLED</span></button><button class="action-btn strike" data-bat-pitch="swinging_strike"><b>헛스윙</b><span>WHIFF</span></button><button class="action-btn" data-bat-pitch="foul"><b>파울</b><span>FOUL</span></button><button class="action-btn inplay" data-bat-pitch="in_play"><b>IN PLAY</b><span>결과 선택</span></button></div><button class="action-btn hbp full" style="margin-top:10px" data-bat-pitch="hbp"><b>사구 HBP</b><span>타석 종료</span></button>`;}
function gameDefenseForm(){return `<div class="entry-title"><div><p class="section-kicker">DEFENSIVE PLAY</p><h2>DEFENSE</h2><p>포구 결과와 송구 품질을 빠르게 기록합니다. 포구 형태는 포지션에 따라 자동으로 바뀝니다.</p></div></div><div class="form-grid"><label>포지션<select id="defPosition"><option>SS</option><option>2B</option><option>3B</option><option>1B</option><option>C</option><option>P</option><option>LF</option><option>CF</option><option>RF</option></select></label><label>타구<select id="defBall"><option value="GB">GB · 땅볼</option><option value="LD">LD · 라인드라이브</option><option value="FB">FB · 뜬공</option><option value="BUNT">번트</option></select></label><label>포구 결과<select id="defFieldResult"><option value="success">성공</option><option value="unstable">불안정</option><option value="failed">실패</option></select></label></div><div class="field-group"><span>포구 형태 (선택)</span><div id="defFieldType" class="chip-grid"></div></div><div class="form-grid"><label>송구<select id="defThrowResult"><option value="none">없음</option><option value="success">정상 송구</option><option value="error">악송구</option></select></label><label>송구 목적지<select id="defThrowTarget"><option value="">선택 안 함</option><option value="1B">1루</option><option value="2B">2루</option><option value="3B">3루</option><option value="HOME">홈</option><option value="RELAY">중계</option></select></label><label>송구 부하<select id="defThrowTLU"><option value="0.75">가벼움 · 0.75</option><option value="0.85" selected>중간 · 0.85</option><option value="1">전력 · 1.00</option></select></label></div><p class="microcopy">송구 없음이면 TLU는 추가되지 않습니다. 정상 송구는 상대 포구 실책과 관계없이 받을 수 있는 위치에 보낸 송구를 뜻합니다.</p><button id="saveDefense" class="save-set">수비 플레이 저장</button>`;}
function gameBaserunningForm(){return `<div class="entry-title"><div><p class="section-kicker">BASERUNNING EVENT</p><h2>BASERUNNING</h2><p>도루는 한 베이스 단위 시도로만 기록합니다.</p></div></div><div class="form-grid" style="margin-top:14px"><label>출발<select id="runFrom"><option value="1B">1루</option><option value="2B">2루</option><option value="3B">3루</option></select></label><label>목표<select id="runTo"><option value="2B">2루</option><option value="3B">3루</option><option value="HOME">홈</option></select></label></div><div id="stealResultGroup" class="field-group"><span>결과</span><div class="chip-grid"><button type="button" class="active" data-steal-result="SUCCESS">성공</button><button type="button" data-steal-result="FAILED">실패</button></div></div><button id="saveBaserunning" class="save-set">도루 기록 저장</button>`;}
function trainingForm(domain){if(domain==='pitching')return trainingPitchingForm();if(domain==='hitting')return trainingHittingForm();if(domain==='defense')return trainingDefenseForm();return trainingBaserunningForm();}
function quantityHtml(value=ui.quantity){return `<div class="quantity-box"><div class="quantity-main"><button type="button" data-qty-delta="-1">−</button><input id="trainingQty" type="number" min="0" step="1" value="${value}" /><button type="button" data-qty-delta="1">＋</button></div><div class="quantity-quick"><button type="button" data-qty-delta="5">+5</button><button type="button" data-qty-delta="10">+10</button><button type="button" data-qty-set="0">초기화</button></div></div>`;}
function trainingPitchingForm(){const a=athlete(),side=a?.throws==='S'?'R':a?.throws||'R';return `<div class="entry-title"><div><p class="section-kicker">THROWING VOLUME</p><h2>투구 훈련</h2><p>훈련 명칭보다 실제 투구 강도와 총량을 기록합니다.</p></div></div><div class="form-grid"><label>투구 방향<select id="trPitchSide"><option value="R" ${side==='R'?'selected':''}>우투</option><option value="L" ${side==='L'?'selected':''}>좌투</option></select></label><label>강도<select id="trPitchIntensity"><option value="light">가벼운 · 0.75 TLU</option><option value="medium">중간 · 0.85 TLU</option><option value="max">전력 · 1.00 TLU</option></select></label></div><div class="field-group"><span>투구 횟수</span>${quantityHtml()}</div><button class="save-set" data-save-training="pitching">훈련 세트 저장</button>`;}
function trainingHittingForm(){const a=athlete(),side=a?.bats==='S'?'R':a?.bats||'R';return `<div class="entry-title"><div><p class="section-kicker">HITTING VOLUME</p><h2>타격 훈련</h2><p>좌·우 타격, 훈련 종류, 필요 시 구속과 스윙량을 기록합니다.</p></div></div><div class="form-grid"><label>타격 방향<select id="trHitSide"><option value="R" ${side==='R'?'selected':''}>우타</option><option value="L" ${side==='L'?'selected':''}>좌타</option></select></label><label>훈련 종류<select id="trHitType"><option value="DRY_SWING">빈스윙</option><option value="TEE">티</option><option value="TOSS">토스</option><option value="BP">배팅볼</option><option value="MACHINE">머신</option><option value="LIVE">라이브</option></select></label><label>구속 km/h (선택)<input id="trHitVelocity" type="number" min="0" max="200" placeholder="예: 90" /></label></div><div class="field-group"><span>스윙 횟수</span>${quantityHtml()}</div><button class="save-set" data-save-training="hitting">훈련 세트 저장</button>`;}
function trainingDefenseForm(){return `<div class="entry-title"><div><p class="section-kicker">DEFENSE VOLUME</p><h2>수비 훈련</h2><p>수비 reps와 실제 송구 횟수를 분리해 TLU 중복을 방지합니다.</p></div></div><div class="form-grid"><label>영역<select id="trDefArea"><option value="IF">내야</option><option value="OF">외야</option></select></label><label>훈련 종류<select id="trDefType"><option value="FIELDING">포구</option><option value="THROWING">송구</option><option value="GROUND_BALL">땅볼</option><option value="FLY_BALL">플라이</option><option value="DOUBLE_PLAY">병살</option><option value="RELAY">중계플레이</option><option value="FOOTWORK">풋워크</option><option value="OTHER">기타</option></select></label></div><div class="field-group"><span>훈련 Reps</span>${quantityHtml()}</div><div class="form-grid"><label>실제 송구 횟수<input id="trDefThrowCount" type="number" min="0" value="0" /></label><label>송구 부하<select id="trDefThrowIntensity"><option value="0.75">근거리 · 0.75</option><option value="0.85">중거리 · 0.85</option><option value="1">장거리/전력 · 1.00</option></select></label></div><button class="save-set" data-save-training="defense">훈련 세트 저장</button>`;}
function trainingBaserunningForm(){return `<div class="entry-title"><div><p class="section-kicker">RUNNING VOLUME</p><h2>주루 훈련</h2><p>도루 스타트·리드·슬라이딩·스프린트 등 훈련량을 세트로 기록합니다.</p></div></div><div class="form-grid"><label>훈련 종류<select id="trRunType"><option value="STEAL_START">도루 스타트</option><option value="LEAD_REACTION">리드/반응</option><option value="BASE_RUNNING">베이스러닝</option><option value="SLIDING">슬라이딩</option><option value="SPRINT">스프린트</option><option value="OTHER">기타</option></select></label><label>거리 m (선택)<input id="trRunDistance" type="number" min="0" /></label><label>최고 기록 sec (선택)<input id="trRunBest" type="number" min="0" step="0.01" /></label></div><div class="field-group"><span>횟수</span>${quantityHtml()}</div><button class="save-set" data-save-training="baserunning">훈련 세트 저장</button>`;}

function renderRecent(){
  const records=collectTimeline({date:ui.inputDate,mode:ui.inputMode,domain:ui.domain}).slice(0,8);const el=$('#recentInputList');
  if(!records.length){el.innerHTML='<div class="scope-note">아직 입력된 기록이 없습니다.</div>';return;}
  el.innerHTML=records.map(recordRowHtml).join('');
}
function collectTimeline({date='all',mode='all',domain='all'}={}){
  const out=[];
  for(const e of active(data.gameEvents).filter(x=>x.athleteId===activeAthleteId)){
    if(date!=='all'&&e.activityDate!==date)continue;if(mode==='training')continue;if(domain!=='all'&&e.domain!==domain)continue;out.push({store:'gameEvents',id:e.id,activityDate:e.activityDate,recordedAt:e.recordedAt,mode:'game',domain:e.domain,label:gameEventLabel(e),sub:gameEventSub(e)});
  }
  for(const s of active(data.trainingSets).filter(x=>x.athleteId===activeAthleteId)){
    if(date!=='all'&&s.activityDate!==date)continue;if(mode==='game')continue;if(domain!=='all'&&s.domain!==domain)continue;out.push({store:'trainingSets',id:s.id,activityDate:s.activityDate,recordedAt:s.recordedAt,mode:'training',domain:s.domain,label:trainingSetLabel(s),sub:trainingSetSub(s)});
  }
  // Context parents are shown in full history to make side corrections easy.
  if(mode!=='training'&&(domain==='all'||domain==='pitching'))for(const b of active(data.batterFaced).filter(x=>x.athleteId===activeAthleteId&&x.completed)){
    if(date!=='all'&&b.activityDate!==date)continue;out.push({store:'batterFaced',id:b.id,activityDate:b.activityDate,recordedAt:b.updatedAt,mode:'game',domain:'pitching',label:`타자 #${b.sequenceNo} 종료 · ${b.result||'완료'}`,sub:`내 ${sideThrow(b.pitcherSide)} · 상대 ${sideBat(b.batterSide)} · ${bfEvents(b.id).length}구`,context:true});
  }
  if(mode!=='training'&&(domain==='all'||domain==='hitting'))for(const p of active(data.plateAppearances).filter(x=>x.athleteId===activeAthleteId&&x.completed)){
    if(date!=='all'&&p.activityDate!==date)continue;out.push({store:'plateAppearances',id:p.id,activityDate:p.activityDate,recordedAt:p.updatedAt,mode:'game',domain:'hitting',label:`타석 #${p.sequenceNo} 종료 · ${p.result||'완료'}`,sub:`${sideBat(p.batterSide)} · 상대 ${sideThrow(p.pitcherSide)} · ${paEvents(p.id).length}구`,context:true});
  }
  return out.sort((a,b)=>b.activityDate.localeCompare(a.activityDate)||new Date(b.recordedAt)-new Date(a.recordedAt));
}
function sideThrow(v){return v==='R'?'우투':v==='L'?'좌투':'미입력';}function sideBat(v){return v==='R'?'우타':v==='L'?'좌타':'미입력';}
function gameEventLabel(e){
  if(e.domain==='pitching'){if(e.eventType==='inplay')return `투구 · IN PLAY · ${e.metadata?.result||''}`;return `투구 · ${LABELS[e.eventType]||e.eventType}`;}
  if(['hitting','batting'].includes(e.domain)){if(e.eventType==='in_play')return `타격 · IN PLAY · ${e.metadata?.result||''}`;return `타격 · ${LABELS[e.eventType]||e.eventType}`;}
  if(e.domain==='defense')return `수비 · ${fieldResultLabel(e.metadata?.fieldingResult)} / ${throwResultLabel(e.metadata?.throwResult)}`;
  if(e.domain==='baserunning')return e.eventType==='steal_attempt'?`도루 ${e.metadata?.from||''}→${e.metadata?.to||''} · ${e.metadata?.result==='SUCCESS'?'성공':'실패'}`:`추가 진루 ${e.metadata?.from||''}→${e.metadata?.to||''}`;
  return e.eventType;
}
function gameEventSub(e){const pieces=[`${fmtDate(e.activityDate)} 경기`];if(e.domain==='pitching')pieces.push(`TLU ${n2(GAME_TLU[e.eventType]||e.metadata?.tlu||0)}`);if(e.metadata?.battedBall)pieces.push(e.metadata.battedBall);if(e.metadata?.direction)pieces.push({L:'좌',C:'중',R:'우'}[e.metadata.direction]||e.metadata.direction);return pieces.join(' · ');}
function trainingSetLabel(s){return `${DOMAIN_LABEL[s.domain]} 훈련 · ${LABELS[s.trainingType]||s.trainingType}`;}
function trainingSetSub(s){const bits=[`${s.quantity} ${s.unit==='throws'?'throws':s.unit==='swings'?'swings':'reps'}`];if(s.side)bits.push(s.domain==='pitching'?sideThrow(s.side):sideBat(s.side));if(s.metadata?.velocity)bits.push(`${s.metadata.velocity} km/h`);if(Number(s.tluTotal))bits.push(`${n2(s.tluTotal)} TLU`);return bits.join(' · ');}
function fieldResultLabel(v){return v==='success'?'포구 성공':v==='unstable'?'포구 불안정':'포구 실패';}function throwResultLabel(v){return v==='success'?'송구 성공':v==='error'?'악송구':'송구 없음';}
function recordRowHtml(r){return `<div class="recent-item"><span class="record-time">${fmtTime(r.recordedAt)}</span><span class="record-icon">${r.mode==='game'?'G':'T'}</span><span class="record-copy"><b>${esc(r.label)}</b><small>${esc(r.sub||'')}</small></span><span class="record-actions"><button data-edit-store="${r.store}" data-edit-id="${r.id}">수정</button>${r.context?'':`<button data-delete-store="${r.store}" data-delete-id="${r.id}">삭제</button>`}</span></div>`;}

function renderHistory(){
  const allDates=[...new Set([...active(data.gameEvents),...active(data.trainingSets),...active(data.batterFaced),...active(data.plateAppearances)].filter(x=>x.athleteId===activeAthleteId).map(x=>x.activityDate))].sort().reverse();
  const sel=$('#historyDate');const old=ui.historyDate;sel.innerHTML='<option value="all">모든 날짜</option>'+allDates.map(d=>`<option value="${d}">${fmtDate(d)}</option>`).join('');sel.value=allDates.includes(old)?old:'all';ui.historyDate=sel.value;
  $$('#historyMode button').forEach(b=>b.classList.toggle('active',b.dataset.historyMode===ui.historyMode));$$('#historyDomain button').forEach(b=>b.classList.toggle('active',b.dataset.historyDomain===ui.historyDomain));
  const rows=collectTimeline({date:ui.historyDate,mode:ui.historyMode,domain:ui.historyDomain});$('#historyCount').textContent=`${rows.length} records`;const el=$('#historyList');
  if(!rows.length){el.innerHTML='<div class="scope-note">조건에 맞는 기록이 없습니다.</div>';return;}
  const groups=new Map();for(const r of rows){if(!groups.has(r.activityDate))groups.set(r.activityDate,[]);groups.get(r.activityDate).push(r);}el.innerHTML=[...groups.entries()].map(([date,rs])=>`<section class="history-date-group"><div class="history-date-head"><h3>${fmtDate(date)}</h3><span>${rs.length} records</span></div>${rs.map(recordRowHtml).join('')}</section>`).join('');
}

function analysisRange(){const today=todayKey();if(ui.analysisPeriod==='date')return {from:ui.analysisDate,to:ui.analysisDate,label:fmtDate(ui.analysisDate)};if(ui.analysisPeriod==='7')return {from:dateShift(today,-6),to:today,label:'최근 7일'};if(ui.analysisPeriod==='30')return {from:dateShift(today,-29),to:today,label:'최근 30일'};if(ui.analysisPeriod==='season')return {from:`${today.slice(0,4)}-01-01`,to:`${today.slice(0,4)}-12-31`,label:`${today.slice(0,4)} 시즌`};const dates=[...active(data.gameEvents),...active(data.trainingSets),...active(data.batterFaced),...active(data.plateAppearances)].filter(x=>x.athleteId===activeAthleteId).map(x=>x.activityDate).sort();return {from:dates[0]||today,to:dates.at(-1)||today,label:'전체'};}
function renderAnalysis(){
  $$('#analysisSourceTabs button').forEach(b=>b.classList.toggle('active',b.dataset.analysisSource===ui.analysisSource));$$('#analysisPeriodTabs button').forEach(b=>b.classList.toggle('active',b.dataset.period===ui.analysisPeriod));$('#analysisDate').hidden=ui.analysisPeriod!=='date';$('#analysisDate').value=ui.analysisDate;$$('#analysisDomainTabs button').forEach(b=>b.classList.toggle('active',b.dataset.analysisDomain===ui.analysisDomain));renderSideFilters();
  const r=analysisRange(),a=athlete();if(!a)return;
  let metrics=[],options=[],breakdown='';
  if(ui.analysisSource==='game'){
    if(ui.analysisDomain==='pitching'){
      const s=gamePitchingSummary(data,{athleteId:a.id,from:r.from,to:r.to,pitcherSide:ui.ownSide==='all'?null:ui.ownSide,batterSide:ui.oppSide==='all'?null:ui.oppSide});metrics=[['OFFICIAL PITCHES',s.officialPitches],['GAME TLU',n2(s.gameTLU)],['STRIKE%',pct(s.strikePct,1)],['1ST STRIKE',pct(s.firstPitchStrikePct,1)],['BF',s.bf],['K',s.k],['BB',s.bb],['P/BF',s.pitchesPerBatter?Number(s.pitchesPerBatter).toFixed(2):'—']];options=[['officialPitches','Official Pitches'],['gameTLU','Game TLU'],['strikePct','Strike%'],['firstPitchStrikePct','1st Strike%'],['k','K'],['bb','BB']];breakdown=breakdownHtml('타구 결과',s.battedResults);
    } else if(ui.analysisDomain==='hitting'){
      const s=battingSummary(data,{athleteId:a.id,from:r.from,to:r.to,batterSide:ui.ownSide==='all'?null:ui.ownSide,pitcherSide:ui.oppSide==='all'?null:ui.oppSide});metrics=[['PA',s.PA],['H',s.H],['AVG',dec(s.AVG)],['OBP',dec(s.OBP)],['SLG',dec(s.SLG)],['OPS',s.PA?dec(s.OPS):'—'],['WHIFF%',pct(s.whiffPct,1)],['CONTACT%',pct(s.contactPct,1)]];options=[['PA','Plate Appearances'],['H','Hits'],['AVG','AVG'],['OBP','OBP'],['SLG','SLG'],['OPS','OPS'],['swings','Swings'],['whiffPct','Whiff%'],['contactPct','Contact%']];breakdown=breakdownHtml('타격 결과',s.counts);
    } else if(ui.analysisDomain==='defense'){
      const s=defenseSummary(data,{athleteId:a.id,from:r.from,to:r.to});metrics=[['PLAYS',s.plays],['포구 성공률',pct(s.fieldingSuccessPct,1)],['송구 성공률',pct(s.throwSuccessPct,1)],['포구 실패',s.field.failed||0],['악송구',s.throws.error||0],['수비 송구 TLU',n2(s.throwTLU)]];options=[['plays','수비 플레이'],['fieldingSuccessPct','포구 성공률'],['throwSuccessPct','송구 성공률'],['throwTLU','수비 송구 TLU']];breakdown=breakdownHtml('내야 포구 형태',s.ifTypes)+breakdownHtml('외야 접근',s.ofTypes)+defenseThrowTargetTable(s.targetStats)+defenseFieldTypeThrowTable(s.fieldTypeThrowStats);
    } else {
      const s=baserunningSummary(data,{athleteId:a.id,from:r.from,to:r.to});metrics=[['SB',s.sb],['CS',s.cs],['ATTEMPTS',s.attempts],['SB%',pct(s.sbPct,1)]];options=[['sb','SB'],['cs','CS'],['sbPct','SB 성공률']];breakdown='';
    }
  } else {
    const s=trainingSummary(data,{athleteId:a.id,from:r.from,to:r.to,domain:ui.analysisDomain,side:ui.ownSide==='all'?null:ui.ownSide});const d=s.byDomain[ui.analysisDomain]||{sets:0,volume:0,tlu:0};const w=workloadSummary(data,{athleteId:a.id,from:r.from,to:r.to});metrics=[['SETS',d.sets],['VOLUME',d.volume],['DOMAIN TLU',n2(d.tlu)],['TOTAL TLU',n2(w.total)]];options=[['volume','훈련량'],['tlu','종목 TLU'],['total_tlu','전체 TLU'],...Object.keys(s.byType).map(k=>[k,LABELS[k]||k])];breakdown=breakdownHtml('훈련 구성',Object.fromEntries(Object.entries(s.byType).map(([k,v])=>[LABELS[k]||k,v])));
    if(ui.analysisDomain==='defense')breakdown+=breakdownHtml('내야 / 외야',{'내야':s.byArea.IF||0,'외야':s.byArea.OF||0});
    if(['pitching','hitting'].includes(ui.analysisDomain))breakdown+=breakdownHtml('좌우 비중',{[ui.analysisDomain==='pitching'?'우투':'우타']:s.bySide.R||0,[ui.analysisDomain==='pitching'?'좌투':'좌타']:s.bySide.L||0});
    if(ui.analysisDomain==='pitching')breakdown+=breakdownHtml('TLU 원천',{'경기 공식투구':w.officialPitchTLU,'견제':w.pickoffTLU,'경기 연습투구':w.warmupTLU,'경기 수비송구':w.gameDefenseThrowing,'투구 훈련':w.pitchingTraining,'훈련 수비송구':w.defenseThrowing});
  }
  $('#analysisMetrics').innerHTML=metrics.map(([k,v])=>`<div class="metric-card"><span>${k}</span><b>${v}</b><small>${r.label}</small></div>`).join('');
  const select=$('#metricSelect'),previous=select.value;select.innerHTML=options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');if(options.some(x=>x[0]===previous))select.value=previous;renderChart();$('#analysisBreakdown').innerHTML=breakdown||'<p class="scope-note">선택한 항목에 추가 분해 데이터가 없습니다.</p>';
}
function breakdownHtml(title,obj){const entries=Object.entries(obj||{}).filter(([,v])=>Number(v)>0);if(!entries.length)return '';return `<h3>${esc(title)}</h3><div class="breakdown-grid">${entries.map(([k,v])=>`<div class="breakdown-item"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}</div>`;}
function defenseThrowTargetTable(stats){const labels={'1B':'1루','2B':'2루','3B':'3루',HOME:'홈',RELAY:'중계'};const rows=Object.entries(stats||{}).filter(([,x])=>x.attempts>0);if(!rows.length)return '';return `<h3>송구 목적지별</h3><div class="analysis-table-wrap"><table class="analysis-table"><thead><tr><th>목적지</th><th>시도</th><th>정상</th><th>악송구</th><th>성공률</th></tr></thead><tbody>${rows.map(([k,x])=>`<tr><td>${labels[k]||esc(k)}</td><td>${x.attempts}</td><td>${x.success}</td><td>${x.error}</td><td>${pct(x.successPct,1)}</td></tr>`).join('')}</tbody></table></div>`;}
function defenseFieldTypeThrowTable(stats){const labels={FRONT:'정면',FOREHAND:'포핸드',BACKHAND:'백핸드',CHARGE:'전진',FORWARD:'앞으로',STRAIGHT:'정면',LATERAL:'좌우',BACK:'뒤로'};const rows=Object.entries(stats||{}).filter(([,x])=>x.attempts>0);if(!rows.length)return '';return `<h3>포구 형태 후 송구</h3><div class="analysis-table-wrap"><table class="analysis-table"><thead><tr><th>포구 형태</th><th>시도</th><th>정상</th><th>악송구</th><th>성공률</th></tr></thead><tbody>${rows.map(([k,x])=>`<tr><td>${labels[k]||esc(k)}</td><td>${x.attempts}</td><td>${x.success}</td><td>${x.error}</td><td>${pct(x.successPct,1)}</td></tr>`).join('')}</tbody></table></div>`;}
function renderSideFilters(){const el=$('#sideFilters');if(ui.analysisSource==='game'&&ui.analysisDomain==='pitching'){el.innerHTML=sideFilterHtml('내 투구','own','throw')+sideFilterHtml('상대 타자','opp','bat');}else if(ui.analysisSource==='game'&&ui.analysisDomain==='hitting'){el.innerHTML=sideFilterHtml('내 타격','own','bat')+sideFilterHtml('상대 투수','opp','throw');}else if(ui.analysisSource==='training'&&['pitching','hitting'].includes(ui.analysisDomain)){el.innerHTML=sideFilterHtml(ui.analysisDomain==='pitching'?'투구 방향':'타격 방향','own',ui.analysisDomain==='pitching'?'throw':'bat');ui.oppSide='all';}else{el.innerHTML='';ui.ownSide='all';ui.oppSide='all';}}
function sideFilterHtml(label,key,type){const cur=key==='own'?ui.ownSide:ui.oppSide;return `<div class="side-filter-block"><span>${label}</span><button data-analysis-side="${key}:all" class="${cur==='all'?'active':''}">전체</button><button data-analysis-side="${key}:R" class="${cur==='R'?'active':''}">${type==='throw'?'우투':'우타'}</button><button data-analysis-side="${key}:L" class="${cur==='L'?'active':''}">${type==='throw'?'좌투':'좌타'}</button></div>`;}
function renderChart(){const a=athlete();if(!a)return;const r=analysisRange(),metric=$('#metricSelect').value||'volume';let series=[];if(ui.analysisSource==='training'){series=seriesByDate(data,{athleteId:a.id,from:r.from,to:r.to,source:'training',domain:ui.analysisDomain,metric});}else{series=seriesByDate(data,{athleteId:a.id,from:r.from,to:r.to,source:ui.analysisDomain,metric,batterSide:ui.analysisDomain==='pitching'?(ui.oppSide==='all'?null:ui.oppSide):(ui.ownSide==='all'?null:ui.ownSide),pitcherSide:ui.analysisDomain==='pitching'?(ui.ownSide==='all'?null:ui.ownSide):(ui.oppSide==='all'?null:ui.oppSide)});}$('#chartTitle').textContent=`${$('#metricSelect').selectedOptions[0]?.textContent||'추이'} · ${r.label}`;$('#mainChart').innerHTML=svgLineChart(series,metric);}
function svgLineChart(series,metric=''){if(!series.length)return '<div class="chart-empty">표시할 데이터가 없습니다.</div>';const W=900,H=260,pad={l:48,r:18,t:18,b:36},decimalMetric=['AVG','OBP','SLG','OPS'].includes(metric),maxValue=Math.max(...series.map(x=>x.value)),max=decimalMetric?Math.max(1,maxValue):Math.max(1,maxValue);const pts=series.map((x,i)=>{const px=pad.l+(W-pad.l-pad.r)*(series.length===1?.5:i/(series.length-1)),py=pad.t+(H-pad.t-pad.b)*(1-x.value/max);return {...x,x:px,y:py};});const path=pts.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' ');const every=Math.max(1,Math.ceil(series.length/6));return `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img"><line x1="${pad.l}" y1="${H-pad.b}" x2="${W-pad.r}" y2="${H-pad.b}" stroke="#dce5ec"/><line x1="${pad.l}" y1="${pad.t}" x2="${pad.l}" y2="${H-pad.b}" stroke="#dce5ec"/><path d="${path}" fill="none" stroke="#1565d8" stroke-width="4" vector-effect="non-scaling-stroke"/>${pts.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="4" fill="#fff" stroke="#1565d8" stroke-width="3" vector-effect="non-scaling-stroke"/>${i%every===0||i===pts.length-1?`<text x="${p.x}" y="${H-12}" text-anchor="middle" fill="#718396" font-size="12">${fmtShort(p.date)}</text>`:''}`).join('')}<text x="${pad.l-8}" y="${pad.t+5}" text-anchor="end" fill="#718396" font-size="12">${formatChartVal(max,metric)}</text><text x="${pad.l-8}" y="${H-pad.b}" text-anchor="end" fill="#718396" font-size="12">${formatChartVal(0,metric)}</text></svg>`;}
function formatChartVal(v,metric=''){if(['AVG','OBP','SLG','OPS'].includes(metric)){const n=Number(v).toFixed(3);return n.startsWith('0.')?n.slice(1):n;}if(['strikePct','firstPitchStrikePct','fieldingSuccessPct','throwSuccessPct','sbPct','whiffPct','contactPct'].includes(metric))return `${Number(v).toFixed(v%1?1:0)}%`;return v>=1000?(v/1000).toFixed(1)+'k':Number(v.toFixed(1));}

function renderSettings(){
  const ats=active(data.athletes);$('#athleteCount').textContent=`${ats.length}명`;$('#athleteList').innerHTML=ats.map(a=>athleteRow(a)).join('');$('#athletePickerList').innerHTML=ats.map(a=>athleteRow(a,true)).join('');renderCloudUI();
}
function athleteRow(a,picker=false){return `<div class="athlete-row ${a.id===activeAthleteId?'active':''}"><span class="athlete-avatar">${esc(a.name.slice(0,1))}</span><span class="copy"><b>${esc(a.name)}</b><small>${a.number?`#${esc(a.number)} · `:''}${esc(a.team||'팀 미입력')} · ${sideThrow(a.throws)}/${sideBat(a.bats)}</small></span>${picker?`<button data-pick-athlete="${a.id}">선택</button>`:`<button data-edit-athlete="${a.id}">수정</button>`}</div>`;}

function bindStaticEvents(){
  if(staticEventsBound)return;staticEventsBound=true;
  $$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.nav)));$$('[data-quick]').forEach(b=>b.addEventListener('click',()=>{ui.inputMode=b.dataset.quick;ui.inputDate=todayKey();setView('input');renderInput();}));
  $('#activityDateInput').addEventListener('change',e=>{ui.inputDate=e.target.value||todayKey();renderInput();});
  $$('#inputModeTabs button').forEach(b=>b.addEventListener('click',()=>{ui.inputMode=b.dataset.mode;renderInput();}));
  $$('#domainTabs button').forEach(b=>b.addEventListener('click',()=>{ui.domain=b.dataset.domain;renderInput();}));
  $('#openDateLogs').addEventListener('click',()=>{ui.historyDate=ui.inputDate;ui.historyMode=ui.inputMode;ui.historyDomain=ui.domain;setView('history');});
  $('#historyDate').addEventListener('change',e=>{ui.historyDate=e.target.value;renderHistory();});$$('#historyMode button').forEach(b=>b.addEventListener('click',()=>{ui.historyMode=b.dataset.historyMode;renderHistory();}));$$('#historyDomain button').forEach(b=>b.addEventListener('click',()=>{ui.historyDomain=b.dataset.historyDomain;renderHistory();}));
  $$('#analysisSourceTabs button').forEach(b=>b.addEventListener('click',()=>{ui.analysisSource=b.dataset.analysisSource;renderAnalysis();}));$$('#analysisPeriodTabs button').forEach(b=>b.addEventListener('click',()=>{ui.analysisPeriod=b.dataset.period;renderAnalysis();}));$('#analysisDate').addEventListener('change',e=>{ui.analysisDate=e.target.value||todayKey();renderAnalysis();});$$('#analysisDomainTabs button').forEach(b=>b.addEventListener('click',()=>{ui.analysisDomain=b.dataset.analysisDomain;ui.ownSide='all';ui.oppSide='all';renderAnalysis();}));$('#metricSelect').addEventListener('change',renderChart);
  $('#athleteSwitcher').addEventListener('click',()=>showModal('athletePicker'));$('#addAthleteBtn').addEventListener('click',()=>openAthleteModal());$('#pickerAddAthlete').addEventListener('click',()=>{hideModal('athletePicker');openAthleteModal();});$('#athleteForm').addEventListener('submit',saveAthleteForm);$('#deleteAthleteBtn').addEventListener('click',deleteAthleteFromModal);
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>hideModal(b.dataset.close)));document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true;}));
  $('#inPlayResults').addEventListener('click',e=>{const b=e.target.closest('[data-result]');if(b)completeInPlay(b.dataset.result);});
  $('#recordEditForm').addEventListener('submit',saveEditedRecord);
  $('#undoDeleteBtn').addEventListener('click',undoDelete);
  document.body.addEventListener('click',delegatedClick);
  $('#exportData').addEventListener('click',exportBackup);$('#importData').addEventListener('change',importBackup);
  $('#signInBtn').addEventListener('click',signIn);$('#signUpBtn').addEventListener('click',signUp);$('#signOutBtn').addEventListener('click',signOut);$('#syncNowBtn').addEventListener('click',()=>syncCloud(true));$('#cloudPill').addEventListener('click',()=>setView('settings'));
  $('#installApp').addEventListener('click',promptInstall);$('#installMini').addEventListener('click',promptInstall);
  window.addEventListener('online',()=>{renderCloudStatus();scheduleSync(100);});window.addEventListener('offline',renderCloudStatus);
}
function delegatedClick(e){
  const pick=e.target.closest('[data-pick-athlete]');if(pick)return pickAthlete(pick.dataset.pickAthlete);
  const editA=e.target.closest('[data-edit-athlete]');if(editA)return openAthleteModal(editA.dataset.editAthlete);
  const side=e.target.closest('[data-side-kind]');if(side)return setCurrentSide(side.dataset.sideKind,side.dataset.sideValue||null);
  const as=e.target.closest('[data-analysis-side]');if(as){const [k,v]=as.dataset.analysisSide.split(':');if(k==='own')ui.ownSide=v;else ui.oppSide=v;return renderAnalysis();}
  const edit=e.target.closest('[data-edit-store]');if(edit)return openRecordEdit(edit.dataset.editStore,edit.dataset.editId);
  const del=e.target.closest('[data-delete-store]');if(del)return softDeleteRecord(del.dataset.deleteStore,del.dataset.deleteId);
}
function bindDynamicFormEvents(){
  $$('[data-pitch]').forEach(b=>b.addEventListener('click',()=>recordPitch(b.dataset.pitch)));$$('[data-game-throw]').forEach(b=>b.addEventListener('click',()=>recordGameThrow(b.dataset.gameThrow)));$$('[data-bat-pitch]').forEach(b=>b.addEventListener('click',()=>recordBatPitch(b.dataset.batPitch)));
  $('#defPosition')?.addEventListener('change',renderDefenseFieldTypes);renderDefenseFieldTypes();$('#saveDefense')?.addEventListener('click',saveDefensePlay);
  $$('[data-steal-result]').forEach(b=>b.addEventListener('click',()=>{$$('[data-steal-result]').forEach(x=>x.classList.remove('active'));b.classList.add('active');}));$('#runFrom')?.addEventListener('change',syncRunTarget);$('#saveBaserunning')?.addEventListener('click',saveBaserunning);
  $$('[data-qty-delta]').forEach(b=>b.addEventListener('click',()=>changeQty(Number(b.dataset.qtyDelta))));$$('[data-qty-set]').forEach(b=>b.addEventListener('click',()=>setQty(Number(b.dataset.qtySet))));$('#trainingQty')?.addEventListener('input',e=>ui.quantity=Math.max(0,Number(e.target.value)||0));$$('[data-save-training]').forEach(b=>b.addEventListener('click',()=>saveTrainingSet(b.dataset.saveTraining)));
}
function renderDefenseFieldTypes(){const el=$('#defFieldType');if(!el)return;const position=$('#defPosition')?.value||'SS',group=['LF','CF','RF'].includes(position)?'OF':'IF';const vals=group==='IF'?[['FRONT','정면'],['FOREHAND','포핸드'],['BACKHAND','백핸드'],['CHARGE','전진']]:[['FORWARD','앞으로'],['STRAIGHT','정면'],['LATERAL','좌우'],['BACK','뒤로']];el.innerHTML='<button type="button" data-def-field-type="" class="active">미입력</button>'+vals.map(([v,l])=>`<button type="button" data-def-field-type="${v}">${l}</button>`).join('');$$('[data-def-field-type]').forEach(b=>b.addEventListener('click',()=>{$$('[data-def-field-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');}));}
function changeQty(delta){setQty(Math.max(0,(Number($('#trainingQty')?.value)||0)+delta));}function setQty(v){ui.quantity=v;if($('#trainingQty'))$('#trainingQty').value=v;}
function syncRunTarget(){const v=$('#runFrom')?.value;if(!v)return;$('#runTo').value=v==='1B'?'2B':v==='2B'?'3B':'HOME';}

async function setCurrentSide(kind,value){
  if(ui.inputMode!=='game')return;
  if(ui.domain==='pitching'){
    let bf=currentBF();
    if(kind==='batter')ui.pendingBatterSide=value;if(kind==='pitcher')ui.pendingOwnPitchSide=value;
    if(bf){if(kind==='batter')bf.batterSide=value;if(kind==='pitcher')bf.pitcherSide=value;await save('batterFaced',bf,{render:false});}
  } else if(ui.domain==='hitting'){
    let pa=currentPA();
    if(kind==='bat')ui.pendingBatSide=value;if(kind==='oppPitcher')ui.pendingOppPitcherSide=value;
    if(pa){if(kind==='bat')pa.batterSide=value;if(kind==='oppPitcher')pa.pitcherSide=value;await save('plateAppearances',pa,{render:false});}
  }
  renderInput();
}
async function ensureBF(){
  let bf=currentBF();if(bf)return bf;const gd=await ensureGameDay();const a=athlete();bf={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,sequenceNo:nextSequence('batterFaced',ui.inputDate),pitcherSide:ui.pendingOwnPitchSide||(a?.throws==='S'?null:a?.throws),batterSide:ui.pendingBatterSide||null,result:null,completed:false,activityDate:ui.inputDate,recordedAt:iso(),ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('batterFaced',bf,{render:false});ui.pendingBatterSide=null;return bf;
}
async function ensurePA(){
  let pa=currentPA();if(pa)return pa;const gd=await ensureGameDay();const a=athlete(),prev=lastCompleted('pa');pa={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,sequenceNo:nextSequence('plateAppearances',ui.inputDate),batterSide:ui.pendingBatSide||(a?.bats==='S'?null:a?.bats),pitcherSide:ui.pendingOppPitcherSide??prev?.pitcherSide??null,result:null,completed:false,activityDate:ui.inputDate,recordedAt:iso(),ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('plateAppearances',pa,{render:false});ui.pendingBatSide=null;return pa;
}
async function recordPitch(type){
  if(type==='inplay'){ui.inPlayContext='pitching';$('#inPlayTitle').textContent='투구 · 타구 결과';$('#inPlayBallType').value='';$('#inPlayDirection').value='';showModal('inPlayModal');return;}
  const bf=await ensureBF(),gd=await ensureGameDay();const e={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,domain:'pitching',parentType:'batter_faced',parentId:bf.id,eventType:type,activityDate:ui.inputDate,recordedAt:iso(),metadata:{tlu:1},ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('gameEvents',e,{render:false});await maybeCompleteBF(bf);renderAll();
}
async function maybeCompleteBF(bf,forcedResult=null){const ev=bfEvents(bf.id),c=countBS(ev,'pitching');let result=forcedResult;if(!result){if(ev.at(-1)?.eventType==='hbp')result='HBP';else if(c.b>=4)result='BB';else if(c.s>=3)result='K';}if(result){bf.result=result;bf.completed=true;await save('batterFaced',bf,{render:false});showToast('타자 종료',`${ev.length}구 · ${result}`,'complete');}return !!result;}
async function recordGameThrow(type){const gd=await ensureGameDay(),a=athlete(),bf=currentBF();const throwSide=bf?.pitcherSide||ui.pendingOwnPitchSide||(a?.throws==='S'?null:a?.throws)||null;const e={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,domain:'pitching',parentType:null,parentId:null,eventType:type,activityDate:ui.inputDate,recordedAt:iso(),metadata:{tlu:GAME_TLU[type],throwSide},ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('gameEvents',e);}
async function recordBatPitch(type){
  if(type==='in_play'){ui.inPlayContext='batting';$('#inPlayTitle').textContent='타격 · 타구 결과';$('#inPlayBallType').value='';$('#inPlayDirection').value='';showModal('inPlayModal');return;}
  const pa=await ensurePA(),gd=await ensureGameDay();const e={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,domain:'hitting',parentType:'plate_appearance',parentId:pa.id,eventType:type,activityDate:ui.inputDate,recordedAt:iso(),metadata:{},ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('gameEvents',e,{render:false});await maybeCompletePA(pa);renderAll();
}
async function maybeCompletePA(pa,forcedResult=null){const ev=paEvents(pa.id),c=countBS(ev,'batting');let result=forcedResult;if(!result){if(ev.at(-1)?.eventType==='hbp')result='HBP';else if(c.b>=4)result='BB';else if(c.s>=3)result='SO';}if(result){pa.result=result;pa.completed=true;await save('plateAppearances',pa,{render:false});showToast('타석 종료',`${ev.length}구 · ${result}`,'complete');}return !!result;}
async function completeInPlay(result){hideModal('inPlayModal');const bt=$('#inPlayBallType').value,dir=$('#inPlayDirection').value;if(ui.inPlayContext==='pitching'){const bf=await ensureBF(),gd=await ensureGameDay();const e={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,domain:'pitching',parentType:'batter_faced',parentId:bf.id,eventType:'inplay',activityDate:ui.inputDate,recordedAt:iso(),metadata:{result,battedBall:bt||null,direction:dir||null,tlu:1},ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('gameEvents',e,{render:false});await maybeCompleteBF(bf,result);}else{const pa=await ensurePA(),gd=await ensureGameDay();const e={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,domain:'hitting',parentType:'plate_appearance',parentId:pa.id,eventType:'in_play',activityDate:ui.inputDate,recordedAt:iso(),metadata:{result,battedBall:bt||null,direction:dir||null},ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('gameEvents',e,{render:false});await maybeCompletePA(pa,result);}ui.inPlayContext=null;renderAll();}

async function saveDefensePlay(){const gd=await ensureGameDay(),a=athlete(),fieldType=$('[data-def-field-type].active')?.dataset.defFieldType||null,throwResult=$('#defThrowResult').value,hasThrow=['success','error'].includes(throwResult),throwTLU=hasThrow?Number($('#defThrowTLU').value)||0:0,throwSide=a?.throws==='S'?null:(a?.throws||null);const e={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,domain:'defense',parentType:null,parentId:null,eventType:'fielding_play',activityDate:ui.inputDate,recordedAt:iso(),metadata:{position:$('#defPosition').value,battedBall:$('#defBall').value,fieldingResult:$('#defFieldResult').value,fieldingType:fieldType,throwResult,throwTarget:hasThrow?($('#defThrowTarget').value||null):null,throwTLU,throwSide},ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('gameEvents',e);showToast('수비 기록 저장',hasThrow?`플레이 1건 · +${n2(throwTLU)} TLU`:'플레이 1건');}
async function saveBaserunning(){const gd=await ensureGameDay(),from=$('#runFrom').value,to=$('#runTo').value,result=$('[data-steal-result].active')?.dataset.stealResult||'SUCCESS';if(from===to){showToast('베이스를 확인하세요','출발과 목표가 같습니다.');return;}const e={id:uuid(),athleteId:activeAthleteId,gameDayId:gd.id,domain:'baserunning',parentType:null,parentId:null,eventType:'steal_attempt',activityDate:ui.inputDate,recordedAt:iso(),metadata:{from,to,result},ownerId:cloud.session?.user?.id||null,deletedAt:null};await save('gameEvents',e);showToast('도루 기록',`${from}→${to} · ${result==='SUCCESS'?'성공':'실패'}`);}

async function saveTrainingSet(domain){const q=Math.max(0,Number($('#trainingQty')?.value)||0);if(!q){showToast('횟수를 입력하세요');return;}let rec={id:uuid(),athleteId:activeAthleteId,activityDate:ui.inputDate,domain,trainingType:'OTHER',side:null,quantity:q,unit:'reps',tluPerRep:0,tluTotal:0,metadata:{},recordedAt:iso(),ownerId:cloud.session?.user?.id||null,deletedAt:null};
  if(domain==='pitching'){const intensity=$('#trPitchIntensity').value,weights={light:.75,medium:.85,max:1};rec.trainingType='throwing';rec.side=$('#trPitchSide').value;rec.unit='throws';rec.metadata.intensity=intensity;rec.tluPerRep=weights[intensity];rec.tluTotal=round2(q*rec.tluPerRep);}
  else if(domain==='hitting'){rec.trainingType=$('#trHitType').value;rec.side=$('#trHitSide').value;rec.unit='swings';rec.metadata.velocity=Number($('#trHitVelocity').value)||null;}
  else if(domain==='defense'){rec.trainingType=$('#trDefType').value;rec.unit='reps';const throwCount=Math.max(0,Number($('#trDefThrowCount').value)||0),intensity=Number($('#trDefThrowIntensity').value)||0;rec.metadata={area:$('#trDefArea').value,throwCount,throwIntensity:intensity};rec.tluPerRep=0;rec.tluTotal=round2(throwCount*intensity);}
  else {rec.trainingType=$('#trRunType').value;rec.unit='reps';rec.metadata={distanceM:Number($('#trRunDistance').value)||null,bestTime:Number($('#trRunBest').value)||null};}
  await save('trainingSets',rec);showToast('훈련 세트 저장',trainingSetSub(rec));setQty(q);}

function openAthleteModal(id=null){const a=id?data.athletes.find(x=>x.id===id):null;$('#athleteModalTitle').textContent=a?'선수 수정':'선수 추가';$('#athleteId').value=a?.id||'';$('#athleteName').value=a?.name||'';$('#athleteNumber').value=a?.number||'';$('#athleteBirthDate').value=a?.birthDate||'';$('#athleteTeam').value=a?.team||'';$('#athletePosition').value=a?.position||'';$('#athleteThrows').value=a?.throws||'R';$('#athleteBats').value=a?.bats||'R';$('#deleteAthleteBtn').style.visibility=a?'visible':'hidden';showModal('athleteModal');}
async function saveAthleteForm(e){e.preventDefault();const id=$('#athleteId').value||uuid(),old=data.athletes.find(x=>x.id===id);const rec={...(old||{}),id,name:$('#athleteName').value.trim()||'선수',number:$('#athleteNumber').value.trim(),birthDate:$('#athleteBirthDate').value,team:$('#athleteTeam').value.trim(),position:$('#athletePosition').value.trim(),throws:$('#athleteThrows').value,bats:$('#athleteBats').value,ownerId:old?.ownerId||cloud.session?.user?.id||null,deletedAt:null};await save('athletes',rec,{render:false});if(!activeAthleteId){activeAthleteId=id;await setMeta('activeAthleteId',id);}hideModal('athleteModal');renderAll();}
async function deleteAthleteFromModal(){const id=$('#athleteId').value;if(!id)return;const activeA=active(data.athletes);if(activeA.length<=1){showToast('선수는 최소 1명 필요합니다');return;}if(!confirm('이 선수를 삭제할까요? 기록은 복구를 위해 soft-delete 됩니다.'))return;const a=data.athletes.find(x=>x.id===id);a.deletedAt=iso();await save('athletes',a,{render:false});if(activeAthleteId===id){activeAthleteId=active(data.athletes).find(x=>x.id!==id)?.id;await setMeta('activeAthleteId',activeAthleteId);}hideModal('athleteModal');renderAll();}
async function pickAthlete(id){activeAthleteId=id;await setMeta('activeAthleteId',id);hideModal('athletePicker');renderAll();}

async function recomputeParent(parentType,parentId){
  if(parentType==='batter_faced'){
    const bf=data.batterFaced.find(x=>x.id===parentId);if(!bf)return;
    const ev=bfEvents(parentId),c=countBS(ev,'pitching');let result=null;const last=ev.at(-1);
    if(last?.eventType==='hbp')result='HBP';else if(last?.eventType==='inplay')result=last.metadata?.result||'IN_PLAY';else if(c.b>=4)result='BB';else if(c.s>=3)result='K';
    bf.result=result;bf.completed=!!result;await save('batterFaced',bf,{render:false});
  } else if(parentType==='plate_appearance'){
    const pa=data.plateAppearances.find(x=>x.id===parentId);if(!pa)return;
    const ev=paEvents(parentId),c=countBS(ev,'batting');let result=null;const last=ev.at(-1);
    if(last?.eventType==='hbp')result='HBP';else if(last?.eventType==='in_play')result=last.metadata?.result||'IN_PLAY';else if(c.b>=4)result='BB';else if(c.s>=3)result='SO';
    pa.result=result;pa.completed=!!result;await save('plateAppearances',pa,{render:false});
  }
}

async function softDeleteRecord(store,id){const rec=data[store]?.find(x=>x.id===id);if(!rec)return;const backup=JSON.parse(JSON.stringify(rec));rec.deletedAt=iso();await save(store,rec,{render:false});if(store==='gameEvents'&&rec.parentType&&rec.parentId)await recomputeParent(rec.parentType,rec.parentId);lastDeleted={store,record:backup};$('#undoText').textContent='기록을 삭제했습니다.';$('#undoBar').hidden=false;clearTimeout(undoTimer);undoTimer=setTimeout(()=>{$('#undoBar').hidden=true;lastDeleted=null;},5000);renderAll();}
async function undoDelete(){if(!lastDeleted)return;const rec=lastDeleted.record;rec.deletedAt=null;await save(lastDeleted.store,rec,{render:false});if(lastDeleted.store==='gameEvents'&&rec.parentType&&rec.parentId)await recomputeParent(rec.parentType,rec.parentId);lastDeleted=null;$('#undoBar').hidden=true;renderAll();showToast('삭제 취소','기록을 복원했습니다.');}

function openRecordEdit(store,id){const rec=data[store]?.find(x=>x.id===id);if(!rec)return;$('#editRecordStore').value=store;$('#editRecordId').value=id;let html=`<label>활동 날짜<input name="activityDate" type="date" value="${rec.activityDate||todayKey()}" /></label>`;
  if(store==='batterFaced')html+=`<label>내 투구<select name="pitcherSide"><option value="">미입력</option><option value="R" ${rec.pitcherSide==='R'?'selected':''}>우투</option><option value="L" ${rec.pitcherSide==='L'?'selected':''}>좌투</option></select></label><label>상대 타자<select name="batterSide"><option value="">미입력</option><option value="R" ${rec.batterSide==='R'?'selected':''}>우타</option><option value="L" ${rec.batterSide==='L'?'selected':''}>좌타</option></select></label><label>결과<input name="result" value="${esc(rec.result||'')}" /></label>`;
  else if(store==='plateAppearances')html+=`<label>내 타격<select name="batterSide"><option value="">미입력</option><option value="R" ${rec.batterSide==='R'?'selected':''}>우타</option><option value="L" ${rec.batterSide==='L'?'selected':''}>좌타</option></select></label><label>상대 투수<select name="pitcherSide"><option value="">미입력</option><option value="R" ${rec.pitcherSide==='R'?'selected':''}>우투</option><option value="L" ${rec.pitcherSide==='L'?'selected':''}>좌투</option></select></label><label>결과<input name="result" value="${esc(rec.result||'')}" /></label>`;
  else if(store==='trainingSets'){
    html+=`<label>횟수<input name="quantity" type="number" min="0" value="${rec.quantity}" /></label><label>훈련 종류<input name="trainingType" value="${esc(rec.trainingType)}" /></label>`;
    if(['pitching','hitting'].includes(rec.domain))html+=`<label>좌/우<select name="side"><option value="">미입력</option><option value="R" ${rec.side==='R'?'selected':''}>${rec.domain==='pitching'?'우투':'우타'}</option><option value="L" ${rec.side==='L'?'selected':''}>${rec.domain==='pitching'?'좌투':'좌타'}</option></select></label>`;
    if(rec.domain==='pitching')html+=`<label>TLU/회<input name="tluPerRep" type="number" min="0" step="0.05" value="${rec.tluPerRep||0}" /></label>`;
    if(rec.domain==='hitting')html+=`<label>구속 km/h<input name="velocity" type="number" value="${rec.metadata?.velocity||''}" /></label>`;
    if(rec.domain==='defense')html+=`<label>실제 송구 횟수<input name="throwCount" type="number" min="0" value="${rec.metadata?.throwCount||0}" /></label><label>송구 TLU/회<select name="throwIntensity"><option value="0.75" ${Number(rec.metadata?.throwIntensity)===.75?'selected':''}>0.75</option><option value="0.85" ${Number(rec.metadata?.throwIntensity)===.85?'selected':''}>0.85</option><option value="1" ${Number(rec.metadata?.throwIntensity)===1?'selected':''}>1.00</option></select></label>`;
  }
  else if(store==='gameEvents'){html+=`<label>이벤트<input name="eventType" value="${esc(rec.eventType)}" /></label><label class="span-2">메모<input name="note" value="${esc(rec.metadata?.note||'')}" placeholder="영상 분석 메모" /></label>`;if(rec.domain==='pitching'||['hitting','batting'].includes(rec.domain))html+=`<label>타구 결과<input name="result" value="${esc(rec.metadata?.result||'')}" /></label><label>타구 형태<select name="battedBall"><option value="">미입력</option>${['GB','LD','FB'].map(v=>`<option ${rec.metadata?.battedBall===v?'selected':''}>${v}</option>`).join('')}</select></label><label>타구 방향<select name="direction"><option value="">미입력</option>${[['L','좌'],['C','중'],['R','우']].map(([v,l])=>`<option value="${v}" ${rec.metadata?.direction===v?'selected':''}>${l}</option>`).join('')}</select></label><label>구종 (선택)<input name="pitchType" value="${esc(rec.metadata?.pitchType||'')}" /></label><label>구속 km/h (선택)<input name="velocity" type="number" value="${rec.metadata?.velocity||''}" /></label><label>위치 (선택)<input name="zone" value="${esc(rec.metadata?.zone||'')}" /></label>`;if(rec.domain==='pitching'&&!rec.parentId)html+=`<label>투구 방향<select name="throwSide"><option value="">미입력</option><option value="R" ${rec.metadata?.throwSide==='R'?'selected':''}>우투</option><option value="L" ${rec.metadata?.throwSide==='L'?'selected':''}>좌투</option></select></label>`;if(rec.domain==='defense')html+=`<label>포지션<select name="position">${['SS','2B','3B','1B','C','P','LF','CF','RF'].map(v=>`<option ${rec.metadata?.position===v?'selected':''}>${v}</option>`).join('')}</select></label><label>포구 결과<select name="fieldingResult">${[['success','성공'],['unstable','불안정'],['failed','실패']].map(([v,l])=>`<option value="${v}" ${rec.metadata?.fieldingResult===v?'selected':''}>${l}</option>`).join('')}</select></label><label>포구 형태<select name="fieldingType"><option value="">미입력</option>${[['FRONT','정면'],['FOREHAND','포핸드'],['BACKHAND','백핸드'],['CHARGE','전진'],['FORWARD','앞으로'],['STRAIGHT','정면(외야)'],['LATERAL','좌우'],['BACK','뒤로']].map(([v,l])=>`<option value="${v}" ${rec.metadata?.fieldingType===v?'selected':''}>${l}</option>`).join('')}</select></label><label>송구<select name="throwResult">${[['none','없음'],['success','정상 송구'],['error','악송구']].map(([v,l])=>`<option value="${v}" ${rec.metadata?.throwResult===v?'selected':''}>${l}</option>`).join('')}</select></label><label>송구 목적지<select name="throwTarget"><option value="">미입력</option>${[['1B','1루'],['2B','2루'],['3B','3루'],['HOME','홈'],['RELAY','중계']].map(([v,l])=>`<option value="${v}" ${rec.metadata?.throwTarget===v?'selected':''}>${l}</option>`).join('')}</select></label><label>송구 부하<select name="throwTLU">${[['0.75','0.75'],['0.85','0.85'],['1','1.00']].map(([v,l])=>`<option value="${v}" ${Number(rec.metadata?.throwTLU)===Number(v)?'selected':''}>${l}</option>`).join('')}</select></label>`;}
  $('#recordEditFields').innerHTML=html;showModal('recordEditModal');
}
async function saveEditedRecord(e){e.preventDefault();const store=$('#editRecordStore').value,id=$('#editRecordId').value,rec=data[store].find(x=>x.id===id);if(!rec)return;const fd=new FormData(e.currentTarget),oldDate=rec.activityDate;rec.activityDate=fd.get('activityDate')||rec.activityDate;if(store==='batterFaced'){rec.pitcherSide=fd.get('pitcherSide')||null;rec.batterSide=fd.get('batterSide')||null;rec.result=fd.get('result')||rec.result;}else if(store==='plateAppearances'){rec.batterSide=fd.get('batterSide')||null;rec.pitcherSide=fd.get('pitcherSide')||null;rec.result=fd.get('result')||rec.result;}else if(store==='trainingSets'){rec.quantity=Math.max(0,Number(fd.get('quantity'))||0);rec.trainingType=fd.get('trainingType')||rec.trainingType;rec.metadata=rec.metadata||{};if(fd.has('side'))rec.side=fd.get('side')||null;if(rec.domain==='pitching'){rec.tluPerRep=Math.max(0,Number(fd.get('tluPerRep'))||0);rec.tluTotal=round2(rec.quantity*rec.tluPerRep);}else if(rec.domain==='hitting'){rec.metadata.velocity=Number(fd.get('velocity'))||null;rec.tluTotal=0;}else if(rec.domain==='defense'){rec.metadata.throwCount=Math.max(0,Number(fd.get('throwCount'))||0);rec.metadata.throwIntensity=Number(fd.get('throwIntensity'))||0;rec.tluTotal=round2(rec.metadata.throwCount*rec.metadata.throwIntensity);}else rec.tluTotal=0;}else{rec.eventType=fd.get('eventType')||rec.eventType;rec.metadata=rec.metadata||{};for(const k of ['note','result','battedBall','direction','pitchType','zone','throwSide','position','fieldingResult','fieldingType','throwResult','throwTarget']){const v=fd.get(k);if(v!==null)rec.metadata[k]=v||null;}const vel=fd.get('velocity');if(vel!==null)rec.metadata.velocity=vel?Number(vel):null;const throwTLU=fd.get('throwTLU');if(throwTLU!==null)rec.metadata.throwTLU=['success','error'].includes(rec.metadata.throwResult)?Number(throwTLU)||0:0;if(rec.metadata.throwResult==='none')rec.metadata.throwTarget=null;}
  if(oldDate!==rec.activityDate&&['gameEvents','batterFaced','plateAppearances'].includes(store)){const gd=await ensureGameDay(rec.activityDate);rec.gameDayId=gd.id;}
  await save(store,rec,{render:false});
  if(store==='gameEvents'&&rec.parentType&&rec.parentId){
    if(oldDate!==rec.activityDate){const parentStore=rec.parentType==='batter_faced'?'batterFaced':'plateAppearances',parent=data[parentStore].find(x=>x.id===rec.parentId);const gd=await ensureGameDay(rec.activityDate);if(parent){parent.activityDate=rec.activityDate;parent.gameDayId=gd.id;await save(parentStore,parent,{render:false});}for(const sibling of data.gameEvents.filter(x=>x.parentType===rec.parentType&&x.parentId===rec.parentId&&!x.deletedAt)){if(sibling.id!==rec.id){sibling.activityDate=rec.activityDate;sibling.gameDayId=gd.id;await save('gameEvents',sibling,{render:false});}}}
    await recomputeParent(rec.parentType,rec.parentId);
  }
  if(oldDate!==rec.activityDate&&['batterFaced','plateAppearances'].includes(store)){const gd=await ensureGameDay(rec.activityDate);for(const child of data.gameEvents.filter(x=>x.parentId===rec.id&&!x.deletedAt)){child.activityDate=rec.activityDate;child.gameDayId=gd.id;await save('gameEvents',child,{render:false});}}
  hideModal('recordEditModal');renderAll();showToast('기록 수정 완료');}

async function exportBackup(){const out=await snapshot();out.exportedAt=iso();out.version=6;const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`baseball-tracker-v6-${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function importBackup(e){const f=e.target.files?.[0];if(!f)return;try{const raw=JSON.parse(await f.text());if(Number(raw.version||0)!==6&&!raw.athletes)throw new Error('V6 백업 형식이 아닙니다.');if(!confirm('현재 로컬 데이터를 백업 파일로 교체할까요?'))return;await replaceSnapshot(raw);await reloadData();renderAll();showToast('백업 복원 완료');}catch(err){console.error(err);showToast('백업 복원 실패',err.message||'파일을 확인하세요.');}finally{e.target.value='';}}

function cloudConfig(){const c=window.BASEBALL_SUPABASE_CONFIG||{},url=String(c.url||''),key=String(c.publishableKey||'');return {url,key,valid:url.startsWith('https://')&&!url.includes('YOUR-PROJECT')&&key.startsWith('sb_publishable_')};}
function ensureSupabaseSdk(){if(window.supabase?.createClient)return Promise.resolve(true);return new Promise(resolve=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=true;s.onload=()=>resolve(!!window.supabase?.createClient);s.onerror=()=>resolve(false);document.head.appendChild(s);setTimeout(()=>resolve(!!window.supabase?.createClient),8000);});}
async function initCloud(){const cfg=cloudConfig();if(!cfg.valid){cloud.configured=false;renderCloudUI();return;}const ok=await ensureSupabaseSdk();if(!ok){cloud.configured=false;renderCloudStatus('error','Supabase SDK 로드 실패');return;}cloud.configured=true;cloud.client=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:d}=await cloud.client.auth.getSession();cloud.session=d.session||null;cloud.client.auth.onAuthStateChange((event,session)=>{cloud.session=session||null;renderCloudUI();if(session&&['SIGNED_IN','INITIAL_SESSION','USER_UPDATED'].includes(event))scheduleSync(300);});renderCloudUI();if(cloud.session&&navigator.onLine)scheduleSync(300);}
function renderCloudStatus(forceStatus=null,forceText=null){const pill=$('#cloudPill'),badge=$('#cloudBadge');let status=forceStatus,text=forceText;if(!status){if(!cloud.configured){status='local';text='로컬';}else if(!cloud.session){status='local';text='로그인 필요';}else if(!navigator.onLine){status='offline';text='오프라인';}else if(cloud.syncing){status='syncing';text='동기화 중';}else{status='synced';text='동기화됨';}}pill.className=`cloud-pill ${status}`;pill.textContent=text;badge.className=`cloud-badge ${status}`;badge.textContent=text;}
function renderCloudUI(){const cfg=cloudConfig();$('#cloudNotConfigured').hidden=cfg.valid;$('#cloudLoggedOut').hidden=!cfg.valid||!!cloud.session;$('#cloudLoggedIn').hidden=!cloud.session;if(cloud.session)$('#cloudUserEmail').textContent=cloud.session.user.email||'로그인됨';$('#cloudStatusText').textContent=!cfg.valid?'Project URL을 설정하세요.':cloud.session?'여러 기기와 자동 동기화 중':'로그인하면 클라우드 동기화를 사용할 수 있습니다.';$('#cloudLastSync').textContent=cloud.lastSync?`마지막 동기화: ${new Date(cloud.lastSync).toLocaleString('ko-KR')}`:'';renderCloudStatus();}
async function signIn(){if(!cloud.client)return;const email=$('#authEmail').value.trim(),password=$('#authPassword').value;const {error}=await cloud.client.auth.signInWithPassword({email,password});if(error)showToast('로그인 실패',error.message);}
async function signUp(){if(!cloud.client)return;const email=$('#authEmail').value.trim(),password=$('#authPassword').value;const {error}=await cloud.client.auth.signUp({email,password});if(error)showToast('계정 생성 실패',error.message);else showToast('계정 생성 완료','이메일 확인 설정에 따라 즉시 로그인됩니다.');}
async function signOut(){if(cloud.client)await cloud.client.auth.signOut();cloud.session=null;renderCloudUI();}
function scheduleSync(delay=700){if(!cloud.configured||!cloud.session||!navigator.onLine)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncCloud(false),delay);}

const cloudDefs={
  athletes:{table:'athletes',to:r=>({id:r.id,owner_id:r.ownerId,name:r.name,number:r.number||null,birth_date:r.birthDate||null,team:r.team||null,position:r.position||null,throws:r.throws||'R',bats:r.bats||'R',client_updated_at:r.clientUpdatedAt||0,deleted_at:r.deletedAt||null}),from:r=>({id:r.id,ownerId:r.owner_id,name:r.name,number:r.number||'',birthDate:r.birth_date||'',team:r.team||'',position:r.position||'',throws:r.throws||'R',bats:r.bats||'R',clientUpdatedAt:Number(r.client_updated_at||0),updatedAt:r.updated_at,deletedAt:r.deleted_at,dirty:false})},
  gameDays:{table:'game_days_v6',to:r=>({id:r.id,owner_id:r.ownerId,athlete_id:r.athleteId,activity_date:r.activityDate,client_updated_at:r.clientUpdatedAt||0,deleted_at:r.deletedAt||null}),from:r=>({id:r.id,ownerId:r.owner_id,athleteId:r.athlete_id,activityDate:r.activity_date,clientUpdatedAt:Number(r.client_updated_at||0),updatedAt:r.updated_at,deletedAt:r.deleted_at,dirty:false})},
  batterFaced:{table:'batter_faced_v6',to:r=>({id:r.id,owner_id:r.ownerId,athlete_id:r.athleteId,game_day_id:r.gameDayId,activity_date:r.activityDate,sequence_no:r.sequenceNo,pitcher_side:r.pitcherSide||null,batter_side:r.batterSide||null,result:r.result||null,completed:!!r.completed,recorded_at:r.recordedAt||r.updatedAt||iso(),client_updated_at:r.clientUpdatedAt||0,deleted_at:r.deletedAt||null}),from:r=>({id:r.id,ownerId:r.owner_id,athleteId:r.athlete_id,gameDayId:r.game_day_id,activityDate:r.activity_date,sequenceNo:r.sequence_no,pitcherSide:r.pitcher_side,batterSide:r.batter_side,result:r.result,completed:r.completed,recordedAt:r.recorded_at,clientUpdatedAt:Number(r.client_updated_at||0),updatedAt:r.updated_at,deletedAt:r.deleted_at,dirty:false})},
  plateAppearances:{table:'plate_appearances_v6',to:r=>({id:r.id,owner_id:r.ownerId,athlete_id:r.athleteId,game_day_id:r.gameDayId,activity_date:r.activityDate,sequence_no:r.sequenceNo,batter_side:r.batterSide||null,pitcher_side:r.pitcherSide||null,result:r.result||null,completed:!!r.completed,recorded_at:r.recordedAt||r.updatedAt||iso(),client_updated_at:r.clientUpdatedAt||0,deleted_at:r.deletedAt||null}),from:r=>({id:r.id,ownerId:r.owner_id,athleteId:r.athlete_id,gameDayId:r.game_day_id,activityDate:r.activity_date,sequenceNo:r.sequence_no,batterSide:r.batter_side,pitcherSide:r.pitcher_side,result:r.result,completed:r.completed,recordedAt:r.recorded_at,clientUpdatedAt:Number(r.client_updated_at||0),updatedAt:r.updated_at,deletedAt:r.deleted_at,dirty:false})},
  gameEvents:{table:'game_events_v6',to:r=>({id:r.id,owner_id:r.ownerId,athlete_id:r.athleteId,game_day_id:r.gameDayId,activity_date:r.activityDate,domain:r.domain,parent_type:r.parentType||null,parent_id:r.parentId||null,event_type:r.eventType,recorded_at:r.recordedAt,metadata:r.metadata||{},client_updated_at:r.clientUpdatedAt||0,deleted_at:r.deletedAt||null}),from:r=>({id:r.id,ownerId:r.owner_id,athleteId:r.athlete_id,gameDayId:r.game_day_id,activityDate:r.activity_date,domain:r.domain,parentType:r.parent_type,parentId:r.parent_id,eventType:r.event_type,recordedAt:r.recorded_at,metadata:r.metadata||{},clientUpdatedAt:Number(r.client_updated_at||0),updatedAt:r.updated_at,deletedAt:r.deleted_at,dirty:false})},
  trainingSets:{table:'training_sets_v6',to:r=>({id:r.id,owner_id:r.ownerId,athlete_id:r.athleteId,activity_date:r.activityDate,domain:r.domain,training_type:r.trainingType,side:r.side||null,quantity:r.quantity,unit:r.unit,intensity:r.metadata?.intensity||null,tlu_per_rep:r.tluPerRep||0,tlu_total:r.tluTotal||0,metadata:r.metadata||{},recorded_at:r.recordedAt,client_updated_at:r.clientUpdatedAt||0,deleted_at:r.deletedAt||null}),from:r=>({id:r.id,ownerId:r.owner_id,athleteId:r.athlete_id,activityDate:r.activity_date,domain:r.domain,trainingType:r.training_type,side:r.side,quantity:Number(r.quantity||0),unit:r.unit,intensity:r.intensity,tluPerRep:Number(r.tlu_per_rep||0),tluTotal:Number(r.tlu_total||0),metadata:r.metadata||{},recordedAt:r.recorded_at,clientUpdatedAt:Number(r.client_updated_at||0),updatedAt:r.updated_at,deletedAt:r.deleted_at,dirty:false})}
};
async function syncCloud(manual=false){if(cloud.syncing||!cloud.client||!cloud.session||!navigator.onLine)return;cloud.syncing=true;renderCloudStatus();try{const uid=cloud.session.user.id;
  // On a fresh device, do not upload the auto-created placeholder if the account already has athletes.
  const remoteAth=await cloud.client.from('athletes').select('*').eq('owner_id',uid);if(remoteAth.error)throw remoteAth.error;
  const noActivity=storeNames.slice(1).every(s=>data[s].filter(x=>!x.deletedAt).length===0),localActive=active(data.athletes);
  if((remoteAth.data||[]).length&&noActivity&&localActive.length===1&&localActive[0].name==='선수 1'&&!localActive[0].ownerId){
    await deleteOne('athletes',localActive[0].id);data.athletes=(remoteAth.data||[]).map(cloudDefs.athletes.from);await putMany('athletes',data.athletes);activeAthleteId=data.athletes.find(x=>!x.deletedAt)?.id||null;await setMeta('activeAthleteId',activeAthleteId);
  }
  // Claim local records for the current account.
  for(const store of storeNames){for(const rec of data[store].filter(x=>!x.ownerId)){rec.ownerId=uid;rec.dirty=true;rec.clientUpdatedAt=Date.now();await putOne(store,rec);}}
  // Upload in FK order.
  for(const store of storeNames){const def=cloudDefs[store],dirty=data[store].filter(x=>x.ownerId===uid&&x.dirty);if(!dirty.length)continue;for(let i=0;i<dirty.length;i+=100){const chunk=dirty.slice(i,i+100),{error}=await cloud.client.from(def.table).upsert(chunk.map(def.to),{onConflict:'id'});if(error)throw error;for(const rec of chunk){rec.dirty=false;await putOne(store,rec);}}}
  // Pull and merge by client timestamp.
  for(const store of storeNames){const def=cloudDefs[store],{data:rows,error}=await cloud.client.from(def.table).select('*').eq('owner_id',uid);if(error)throw error;const localMap=new Map(data[store].map(x=>[x.id,x]));for(const row of rows||[]){const remote=def.from(row),local=localMap.get(remote.id);if(!local||Number(remote.clientUpdatedAt)>=Number(local.clientUpdatedAt||0)){await putOne(store,remote);localMap.set(remote.id,remote);}}data[store]=[...localMap.values()];}
  cloud.lastSync=Date.now();localStorage.setItem('btV6LastSync',cloud.lastSync);renderAll();renderCloudUI();if(manual)showToast('동기화 완료','클라우드와 기록을 맞췄습니다.');
 }catch(err){console.error(err);renderCloudStatus('error','동기화 실패');$('#cloudStatusText').textContent=`동기화 실패: ${err.message||err}`;if(manual)showToast('동기화 실패',err.message||'Supabase 설정을 확인하세요.');}finally{cloud.syncing=false;renderCloudStatus();}}

function registerPWA(){if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installMini').style.display='inline-block';});}
async function promptInstall(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return;}showToast('홈 화면에 추가','브라우저 메뉴의 앱 설치/홈 화면에 추가를 사용하세요.');}

init().catch(err=>{
  console.error('App init failed',err);
  window.__BT_BOOT_ERROR__=err;
  const box=$('#bootError');if(box){box.hidden=false;const span=box.querySelector('span');if(span)span.textContent=`초기화 오류: ${err.message||err}`;}
  try{renderCloudStatus('error','초기화 실패');}catch{}
});
